### PR TITLE
homu test

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e6a9290 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e6a9290 with merge e6a9290...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/copper/builds/159047983)
Approved by: japaric
Pushing e6a929021bac9b30549e91f0feec7b20cacc4634 to master...

**Pull request merged**
