### PR TITLE
add outdated notice to the README

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f19d66d has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f19d66d with merge f19d66d...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/copper/builds/232511694?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing f19d66de46f07b5c97f4cd46aca1d17e2fc11ce5 to master...

**Pull request merged**
