### PR TITLE
Fix dead links in the title

### PR DESCRIPTION
**Pull request by jamesmunns**
It looks like this page changed its names, but the contents didn't.

### CODE REVIEW

**Comment by japaric** [comment]
hmm, this link

```
/copper/linux.html#First%20OpenOCD%20connection
```

breaks local builds (`mdbook serve`). But this, without the leading slash, works fine:

```
linux.html#First%20OpenOCD%20connection
```

Could you try that way instead?

**Comment by jamesmunns** [comment]
@japaric I removed all the leading slashes I can find, because it seems the book is rendered "flat". I'm not sure how to serve your jekyll pages locally, (`jekyll serve` failed at the root), and I am currently trying to figure out how to install mdbook (`brew install mdbook` failed).

**Comment by jamesmunns** [comment]
Sorry for submitting a pull request without proper testing :) I was hoping it would be a more minor fix.

**Comment by jamesmunns** [comment]
Of course mdbook is a cargo crate :D, installing now.

**Comment by jamesmunns** [comment]
@japaric Links seem to work correctly using `mdbook serve` now.

**Comment by japaric** [comment]
@jamesmunns Thank you!

**Pull request merged**
