### PR TITLE
test for homu

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 219a679 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 219a679 with merge 219a679...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 7bc9039 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 7bc9039 with merge 7bc9039...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/copper/builds/159043561), [travis](https://travis-ci.org/japaric/copper/builds/159043561)
Approved by: japaric
Pushing 7bc9039e13e69dd3ff9f33ed9b2b4923521ea4e5 to master...

**Pull request merged**
