### PR TITLE
Added a description of dev boards and some more content around ARM and C

### PR DESCRIPTION
**Pull request by cwoodall**
- Added a section to the "Why ARM" section which addresses arm
  as a good platform more directly. Also some examples of projects
  built with ARM processors
- Added an explanation of what a dev board is to What Dev Board
- Added two bullets to Disadvantages of not using C.
- Fixed a few typos, and made a few clarifying changes to language.

### CODE REVIEW

**Comment by japaric** [comment]
Thanks for the PR! I'm pretty much :+1: about the content but I've sent a PR (cwoodall/copper#1) tweaking the wording a bit further.

**Comment by japaric** [comment]
@homunkulus r+

Thank you @cwoodall!

**Comment by homunkulus** [comment]
:pushpin: Commit 9b998bb has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 9b998bb with merge 9b998bb...

**Comment by japaric** [comment]
The test passed but homu didn't merge it for some reason ...

Merging manually.

**Pull request merged**
