### PR TITLE
test installing openocd and qemu

### PR DESCRIPTION
**Pull request by japaric**
like our installation steps say

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ad98cde has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ad98cde with merge ad98cde...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/copper/builds/146556152)

**Pull request merged**
