### PR TITLE
use `cross`

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 001582e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 001582e with merge 001582e...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/copper/builds/187942201)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d2828c5 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d2828c5 with merge d2828c5...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/copper/builds/187944728)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:bulb: This pull request was already approved, no need to approve it again.

- This pull request previously failed. You should add more commits to fix the bug, or use `retry` to trigger a build again.

**Comment by homunkulus** [comment]
:pushpin: Commit d2828c5 has been approved by `japaric`

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ede55d5 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ede55d5 with merge ede55d5...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/copper/builds/187965056)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit c79e0b0 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit c79e0b0 with merge c79e0b0...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/copper/builds/187968714)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 84e1526 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 84e1526 with merge 84e1526...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/copper/builds/187971027)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 24c69d9 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 24c69d9 with merge 24c69d9...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/copper/builds/187971855)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 37be3fa has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 37be3fa with merge 37be3fa...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/copper/builds/187973136)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 26800d4 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 26800d4 with merge 26800d4...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/copper/builds/187974048)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit cc9239c has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit cc9239c with merge cc9239c...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/copper/builds/187974433)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:bulb: This pull request was already approved, no need to approve it again.

- This pull request previously failed. You should add more commits to fix the bug, or use `retry` to trigger a build again.

**Comment by homunkulus** [comment]
:pushpin: Commit 22e384c has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 22e384c with merge 22e384c...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/copper/builds/187975378)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 4f8951e has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 4f8951e with merge 4f8951e...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/copper/builds/187976349)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 3ee88a3 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 3ee88a3 with merge 3ee88a3...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/copper/builds/187978858)
Approved by: japaric
Pushing 3ee88a327c0ac4050be83f499028a8c7682ef6eb to master...

**Pull request merged**
