### PR TITLE
Install GCC ARM Embedded Toolchain via Homebrew Cask

### PR DESCRIPTION
**Pull request by limeburst**
Background: https://github.com/Homebrew/legacy-homebrew/pull/45236

### CODE REVIEW

**Comment by japaric** [comment]
Thanks! Is this `cask` subcommand available in "vanilla" `brew`? Or does the user need to install something extra before using it? If the later, could you add a link to instructions on how to install cask?

**Comment by limeburst** [comment]
It seems Homebrew [automatically taps and keeps Homebrew-Cask updated](https://github.com/caskroom/homebrew-cask/blob/master/USAGE.md#updatingupgrading-the-homebrew-cask-tool).

Just to be sure, I tested this on a clean install of Homebrew. The `cask` subcommand is available in vanilla `brew`, and when invoking it for the first time, Homebrew-Cask is tapped automatically.

**Comment by japaric** [comment]
Awesome, thanks for checking this!

In the near future I'll set up Travis CI to test this repo on a mac builder. I'll use these great tips :smile:.

**Comment by limeburst** [comment]
Thank you for merging!

FYI, I'm just getting started on writing an alternative [controller](https://github.com/limeburst/yuki) for my [keyboard](https://input.club/devices/infinity-keyboard) which has a Kinetis K20.

Your guide has been extremely helpful to MCU newcomers like me who wants to use Rust for their embedded project 😄

Thanks again for writing this guide and [related](https://github.com/japaric/rust-cross) [tools](https://github.com/japaric/xargo)!

**Comment by japaric** [comment]
> FYI, I'm just getting started on writing an alternative controller for my keyboard which has a Kinetis K20.

Awesome! I'll be following that project.

> Thanks again for writing this guide and related tools!

Happy to hear that it's been helpful!

**Pull request merged**
