### PR TITLE
ci: build apps on Linux

### LINKED ISSUE #9: CI: Build apps on nightly
To avoid bitrot

### PR DESCRIPTION
**Pull request by japaric**
closes #9

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit b4e4300 with merge b4e4300...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/japaric/copper/builds/143229124)

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 45e3c88 with merge 45e3c88...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/japaric/copper/builds/143229483)

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit e396c20 with merge e396c20...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/japaric/copper/builds/143230062)

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 5dc61fb with merge c7bedd6...

**Pull request merged**
