### PR TITLE
tweak logic; I disabled builds on "pull requests"

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 308cf82 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 308cf82 with merge 308cf82...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/copper/builds/176592695)
Approved by: japaric
Pushing 308cf8258cc7c94e574115af438276977c5008b8 to master...

**Pull request merged**
