### PR TITLE
ci: build mdbook without default features

### PR DESCRIPTION
**Pull request by japaric**
this speeds up builds and we don't use them anyway

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d7f7633 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d7f7633 with merge d7f7633...

**Comment by japaric** [comment]
@homunkulus r-

**Comment by japaric** [comment]
@homunkulus r- force

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d7f7633 has been approved by `japaric`

**Comment by japaric** [comment]
@homunkulus retry

**Comment by homunkulus** [comment]
:hourglass: Testing commit d7f7633 with merge d7f7633...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d1e6dbd has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d1e6dbd with merge d1e6dbd...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e58f243 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e58f243 with merge e58f243...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 9453060 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 9453060 with merge 9453060...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit c843ea0 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit c843ea0 with merge c843ea0...

**Comment by homunkulus** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/japaric/copper/builds/128734298)

**Pull request merged**
