### PR TITLE
armv6 micros don't have atomics

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 81e1e61 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 81e1e61 with merge 81e1e61...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 65f92f1 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 65f92f1 with merge 65f92f1...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/copper/builds/159024762), [travis](https://travis-ci.org/japaric/copper/builds/159024762)
Approved by: japaric
Pushing 65f92f138c57679d272d6cf0b26b759f6e95ac93 to master...

**Pull request merged**
