### PR TITLE
update text

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus try

**Comment by homunkulus** [comment]
:hourglass: Trying commit 25f33ae with merge 25f33ae...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/copper/builds/175204902)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 488e5e0 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 488e5e0 with merge 488e5e0...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/copper/builds/175254388)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 554cee1 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 554cee1 with merge 554cee1...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/copper/builds/175257201)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 7e2b827 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 7e2b827 with merge 7e2b827...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/copper/builds/175257785)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 0488602 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0488602 with merge 0488602...

**Pull request merged**
